name: Code Check
on: [push]
jobs:
    check:
        runs-on: ubuntu-latest
        env:
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - run: python day1_python.py